### ISSUE TITLE
CMake and Windows build

### ISSUE THREAD

**Issue by mruegenberg** [paperManu/splash#12]
Hi,
I was wondering whether there is a realistic chance of building splash on Windows...

I guess a useful first step would be to switch the build system to CMake. Would you be open to that?

**Comment by paperManu** [comment]
To be honest, I have been wondering about switching to CMake for a few months.
It should not be a lot of work as there is nothing very complicated in the project structure.

Regarding porting Splash to Windows, I don't have time for that but it should be possible. A lot of the dependencies are not mandatory so as long as GLFW, GLM, GSL, ZMQ and Snappy are available, and with a C++11 compiler (which I think MSVCC is), if should not be too much work either. Probably a few platform-specific modifications ...

**Comment by paperManu** [comment]
I made a first draft of using CMake in the cmake branch. It works for me on Mint 17.3, I did not test it on OSX (neither on Windows, of course).

It does not cover everything, so it should really be used as an alternative way of compiling for now. If you have some knowledge of CMake, feel free to submit some improvements!

**Comment by mruegenberg** [comment]
Cool, thanks!

I just tried on OS X and get an error because FindSnappy.cmake is missing. You probably forgot to add `cmake/modules` to Git.

**Comment by paperManu** [comment]
Indeed, I uploaded it.
I also set the minimum CMake version to 3.2 as it seems that 2.8 is very old. Trying to do things correctly ;)

**Comment by mruegenberg** [comment]
I now get an error (line 80 in CMakeLists) because `include/config.h.cmake` does not exist.

**Comment by paperManu** [comment]
Sorry for that, I also forgot to add config.h.cmake.

Did you do a "git submodule update --init" before trying to compile? You should follow the installation wiki, except for the autotools part obviously.

**Comment by mruegenberg** [comment]
Oops, forgot to do the submodules after switching branches...
Unfortunately, that didn't help, even though the zmq.hpp file is there :/

But I found the error :-): In `src/CMakeLists`, the path is `ccpzmq` instead of `cppzmq`.

---------

Also, building Syphon doesn't work. During the CMake run 

    -- Checking for one of the modules 'portaudio-2.0'
    -- Checking for one of the modules 'shmdata-1.2'
    /usr/bin/cd: line 4: cd: syphon: No such file or directory
    2016-04-19 23:24:30.310 xcodebuild[9138:1181033] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2016-04-19 23:24:30.312 xcodebuild[9138:1181033] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    Build settings from command line:
        DSTROOT = /
        SYMROOT = ./build
    
    xcodebuild: error: Unknown build action '$@'.
    
    Splash Configuration

The `cd` error disappaears when using `${CMAKE_SOURCE_DIR}/external/syphon` (which should work regardless of whether the user builds from the source directory or a `build` subdirectory as is common when using CMake.

---------

Also, the need to install gphoto2 should be added to the OS X build instructions, same with portaudio. (They don't seem to be optional, since I got errors without them.)
I also get an error with missing shmdata, even though it should be optional.

---------

Thanks for all your efforb, btw!

**Comment by paperManu** [comment]
I fixed these issues I think.
GPhoto2 is indeed optional, this is fixed too.

Thanks for testing that for me, I will have access to an OSX computer next week so I will be able to test myself before pushing to github.

**Comment by mruegenberg** [comment]
Ok, I got almost to the end of the build :) 

- the `cd` error disappeared, but I still get part of the earlier error: 

        Build settings from command line:
            DSTROOT = /
            SYMROOT = ./build
        
        xcodebuild: error: Unknown build action '$@'.
        
        Splash Configuration

- Probably related, I get a linking error when running make:

        [ 95%] Linking CXX executable splash-scene
        cd /Users/mrueg/Downloads/splash/build/src && /usr/local/Cellar/cmake/3.5.1/bin/cmake -E cmake_link_script CMakeFiles/splash-scene.dir/link.txt --verbose=1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -DGLM_FORCE_RADIANS -DDATADIR=\"/usr/local/share/splash/\" -DSPLASHPREFIX=\"/usr/local\" -F$(top_srcdir)/external/syphon/build/Release -framework Syphon -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/splash-scene.dir/splash-scene.cpp.o  -o splash-scene  libsplash-0.3.a /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib -lglfw3 -lgsl -lgslcblas -lm -lzmq -lgphoto2 -lgphoto2_port -lm -lzmq -lgphoto2 -lgphoto2_port -lavformat -lavcodec -lavutil -lswscale -lportaudio /usr/local/lib/libsnappy.dylib 
        ld: warning: directory not found for option '-F$(top_srcdir)/external/syphon/build/Release'
        Undefined symbols for architecture x86_64:
          "_CGLGetCurrentContext", referenced from:
              Splash::SyphonReceiver::getFrame() in libsplash-0.3.a(texture_syphon_client.mm.o)
          "_OBJC_CLASS_$_NSDate", referenced from:
              objc-class-ref in libsplash-0.3.a(texture_syphon_client.mm.o)
          "_OBJC_CLASS_$_NSRunLoop", referenced from:
              objc-class-ref in libsplash-0.3.a(texture_syphon_client.mm.o)
          ... 

You'll probably find the remaining issues quickly when you can test yourself.

**Comment by paperManu** [comment]
Hi,
As far as I can tell, I have fixed all compilation issues. Splash runs on OSX, although I did not do any extensive tests.

There is one small issue though: Syphon is built along Splash, and it is rebuilt when installing. This new build is done as sudo, so one has to delete the files in splash/external/syphon/build before rebuilding as a normal user.

If by any chance you know how to prevent rebuilding when installing, I'm all ears ;)

**Comment by mruegenberg** [comment]
Not sure how to fix the Syphon problem, but that shouldn't be a huge problem as long as it's mentioned in the readme. Most users would probably only want to build once anyway.
The build also worked on my OS X machine without any additional changes.

One last thing that might be good to fix is possible problems with newer FFMPEG versions (ffmpeg 3). 
The build worked on my Arch Linux machine only when doing `export PKG_CONFIG_PATH=/usr/lib/ffmpeg2.8/pkgconfig:$PKG_CONFIG_PATH` before calling `make` to force the older FFMPEG version to be found first. 
Otherwise, I had the following error:

    ~/Downloads/splash/src/image_ffmpeg.cpp: In member function ‘void     Splash::Image_FFmpeg::readLoop()’:
    ~/Downloads/splash/src/image_ffmpeg.cpp:238:33: error: ‘avcodec_alloc_frame’ was not declared in this scope
         frame = avcodec_alloc_frame();

**Comment by paperManu** [comment]
Alright, I'm not sure how I feel about having two build systems for the same sources, but I don't see any way to get rid of autotools yet as it provides some really useful tools for packaging on Ubuntu. So I think I'll merge the cmake branch into develop and keep both of them alive for now.

I'm aware of the issue with ffmpeg, I'll have to handle both version for now. Could you please create another ticket for this specific issue?
