### ISSUE TITLE
Changing Xorg screen

### ISSUE THREAD

**Issue by nlowe** [paperManu/splash#35]
Hello! I wanted to test out splash on my laptop, which has both intel integrated graphics as well as an nvidia mobile graphics card. `primusrun` configures xorg screen 8 for applications to use. However, it seems that splash only looks for displays on screen zero (Changing the `display` settings in `scenes` changes the error message about not being able to connect to screen `:0.<x>`)

My laptop screen is on `:1`, so even if I try to use the integrated graphics I can't get the application to start:

```bash
nathan@nathan-arch aur-splash-bin]$ export DISPLAY=:8
[nathan@nathan-arch aur-splash-bin]$ primusrun splash -d splash.json 

	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.6.4 -

2017-04-25T15:05:12 / [MESSAGE] / World::applyConfig - Starting a Scene in another process
2017-04-25T15:05:12 / [MESSAGE] / splashScene::main - Creating Scene with name local
2017-04-25T15:05:12 /  [DEBUG]  / Scene::Scene - Scene created successfully
No protocol specified
2017-04-25T15:05:12 / [WARNING] / Scene::glfwErrorCallback - X11: Failed to open display :0.0
2017-04-25T15:05:12 /  [ERROR]  / Scene::init - Unable to initialize GLFW
2017-04-25T15:05:17 /  [ERROR]  / World::applyConfig - Timeout when trying to connect to newly spawned scene "local". Exiting.
```

If I understand `glfw` correctly, it looks like monitor 0 is [hard-coded](https://github.com/paperManu/splash/blob/master/src/scene.cpp#L675), is that correct?

**Comment by paperManu** [comment]
Monitor 0 is set in the configuration file (splash.json), you should try changing the "display" parameter in the "scenes" section.

**Comment by nlowe** [comment]
@paperManu Thanks for the prompt response. Perhaps my wording was poor: Changing the display parameter in the scenes section only changes the sub-number. For example, if I set the display to 99, splash will try to use `:0.99`. On my system, my xorg screen is on `:1`.

If I alter https://github.com/paperManu/splash/blob/master/src/world.cpp#L232-L241 and change `DISPLAY=:0.` to `DISPLAY=:1.` I can get the application to launch.

**Comment by paperManu** [comment]
Oh I see, sorry for the misunderstanding.
I never had to work on such a system, with multiple GPUs only the sub-number changes. I'll add a task for this.

**Comment by paperManu** [comment]
This has been solved in the develop branch, and will be available in the next release.

**Comment by landonharris** [comment]
@paperManu I am still having this issue, is there something that needs to be changed to work around it? 
![Screenshot from 2019-03-21 16-08-28](https://user-images.githubusercontent.com/8370016/54785339-fde09200-4bf3-11e9-82b0-a38ad457bf4a.png)

**Comment by paperManu** [comment]
You can force Splash to open on a given display with the `--forceDisplay` option:
```bash
splash --forceDisplay :1.0 configuration.json
```

You can also force the display server  to use, in case you have more than one xscreen. For example, to run all your windows on the display server :1 :
```bash
splash --displayServer 1 configuration.json
```
Note that this last command will work only if the `display` attribute of the `Scene` object is set in the configuration. It should be the case if the configuration has been exported using the Blender addon.

I'll add something about all this in the Wiki soon
